/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class machankura_vsockk_native_VSockImpl */

#ifndef _Included_machankura_vsockk_native_VSockImpl
#define _Included_machankura_vsockk_native_VSockImpl
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     machankura_vsockk_native_VSockImpl
 * Method:    socketCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_machankura_vsockk_native_VSockImpl_socketCreate
(JNIEnv *, jobject);

/*
 * Class:     machankura_vsockk_native_VSockImpl
 * Method:    connect
 * Signature: (Lfr/acinq/lightning/vsock/VSockAddress;)V
 */
JNIEXPORT void JNICALL Java_machankura_vsockk_native_VSockImpl_connect
(JNIEnv *, jobject, jobject);

/*
 * Class:     machankura_vsockk_native_VSockImpl
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_machankura_vsockk_native_VSockImpl_close
(JNIEnv *, jobject);

/*
 * Class:     machankura_vsockk_native_VSockImpl
 * Method:    write
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_machankura_vsockk_native_VSockImpl_write
(JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     machankura_vsockk_native_VSockImpl
 * Method:    read
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_machankura_vsockk_native_VSockImpl_read
        (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     machankura_vsockk_native_VSockImpl
 * Method:    bind
 * Signature: (Lfr/acinq/lightning/vsock/VSockAddress;)V
 */
JNIEXPORT void JNICALL Java_machankura_vsockk_native_VSockImpl_bind
(JNIEnv *, jobject, jobject);

/*
 * Class:     machankura_vsockk_native_VSockImpl
 * Method:    listen
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_machankura_vsockk_native_VSockImpl_listen
(JNIEnv *, jobject, jint);

/*
 * Class:     machankura_vsockk_native_VSockImpl
 * Method:    accept
 * Signature: (Lfr/acinq/lightning/vsock/native/VSockImpl;)V
 */
JNIEXPORT void JNICALL Java_machankura_vsockk_native_VSockImpl_accept
(JNIEnv *, jobject, jobject);

/*
 * Class:     machankura_vsockk_native_VSockImpl
 * Method:    getLocalCid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_machankura_vsockk_native_VSockImpl_getLocalCid
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
